language: php
php:
  - 7.1.11
  #- 7.2 Segfault in PHPUnit, warten auf 7.2.1
  - nightly
install:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader
script:
  - composer coverage
  - composer phpcs
cache:
  directories:
    - $HOME/.composer/cache/files
after_success:
  - bash <(curl -s https://codecov.io/bash)